### ISSUE TITLE
Version 1.0 not working on IOS

### ISSUE THREAD

**Issue by Sammca** [hypery2k/cordova-sqlite-plugin#3]
My phonegap build app using this plugin has started getting a JS error since version 1.0.0. Stating "undefined is not an object (evaluating 'window.sqlitePlugin.openDatabase')".

App works fine rolling back to 0.9.0. My android build is fine on 1.0.0

**Comment by hypery2k** [comment]
which cordova or phone gap version are you using?

**Comment by Sammca** [comment]
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

**Comment by hypery2k** [comment]
should work with version 1.0.1 again. If not try using cordova.plugins.sqlitePlugin.openDatabase

**Comment by cepm-nate** [comment]
Phonegap-version cli-5.2.0 with cordova-plugin-sqlite version:1.1.0 still gives me 
```
TypeError: undefined is not an object (evaluating 'window.sqlitePlugin.openDatabase')
```
as does version 1.0.1. Thankfully 0.9.0 works fine still. This is on iPad running iOS 9.2.

**Comment by hypery2k** [comment]
I've tested and verified it locally within the iOS simulator

**Comment by hypery2k** [comment]
You can use version 1.0.2
